const letters = [
    { latin: "x", entity: "&#x16A5;&#x16B0", name: "Kaunan and Sowilo", symbol: "ᚲᛊ" },
    { latin: "f", entity: "&#x16A0;", name: "Fehu", symbol: "ᚠ" },
    { latin: "u", entity: "&#x16A1;", name: "Uruz", symbol: "ᚢ" },
    { latin: "th", entity: "&#x16A2;", name: "Thurisaz", symbol: "ᚦ" },
    { latin: "a", entity: "&#x16A3;", name: "Ansuz", symbol: "ᚨ" },
    { latin: "r", entity: "&#x16A4;", name: "Raido", symbol: "ᚱ" },
    { latin: "k", entity: "&#x16A5;", name: "Kaunan", symbol: "ᚲ" },
    { latin: "g", entity: "&#x16A6;", name: "Gebo", symbol: "ᚷ" },
    { latin: "w", entity: "&#x16A7;", name: "Wunjo", symbol: "ᚹ" },
    { latin: "h", entity: "&#x16A8;", name: "Hagalaz", symbol: "ᚺ" },
    { latin: "n", entity: "&#x16A9;", name: "Nauthiz", symbol: "ᚾ" },
    { latin: "i", entity: "&#x16AA;", name: "Isa", symbol: "ᛁ" },
    { latin: "j", entity: "&#x16AB;", name: "Jera", symbol: "ᛃ" },
    { latin: "ei", entity: "&#x16AD;", name: "Eihwaz", symbol: "ᛇ" },
    { latin: "p", entity: "&#x16AE;", name: "Perthro", symbol: "ᛈ" },
    { latin: "z", entity: "&#x16AF;", name: "Algiz", symbol: "ᛉ" },
    { latin: "s", entity: "&#x16B0;", name: "Sowilo", symbol: "ᛊ" },
    { latin: "t", entity: "&#x16B1;", name: "Tiwaz", symbol: "ᛏ" },
    { latin: "b", entity: "&#x16B2;", name: "Berkana", symbol: "ᛒ" },
    { latin: "e", entity: "&#x16B3;", name: "Ehwaz", symbol: "ᛖ" },
    { latin: "m", entity: "&#x16B4;", name: "Mannaz", symbol: "ᛗ" },
    { latin: "l", entity: "&#x16B5;", name: "Laguz", symbol: "ᛚ" },
    { latin: "ing", entity: "&#x16B6;", name: "Ingwaz", symbol: "ᛜ" },
    { latin: "d", entity: "&#x16B7;", name: "Dagaz", symbol: "ᛞ" },
    { latin: "o", entity: "&#x16B8;", name: "Othala", symbol: "ᛟ" },
    { latin: " ", entity: "&nbsp;", name: "Space", symbol: " " },
    { latin: ".", entity: ".", name: "Period", symbol: "." },
    { latin: ",", entity: ",", name: "Comma", symbol: "," },
];

export default letters;